/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LoginPayload {
  'password' : string,
  'loginIdentifier' : string,
}
export interface RegisterPayload {
  'username' : string,
  'password' : string,
  'email' : string,
}
export type RegistrationError = { 'emailTaken' : null } |
  { 'alreadyRegistered' : null } |
  { 'unknown' : null } |
  { 'usernameTaken' : null };
export type RegistrationResult = { 'error' : RegistrationError } |
  { 'success' : null };
export interface Session {
  'token' : string,
  'expiresAt' : bigint,
  'email' : string,
}
export interface UserProfile {
  'customStatus' : string,
  'aboutMe' : string,
  'name' : string,
  'badges' : Array<string>,
  'avatarUrl' : string,
  'bannerUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[LoginPayload], [] | [Session]>,
  'register' : ActorMethod<[RegisterPayload], RegistrationResult>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];