/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'customStatus' : IDL.Text,
  'aboutMe' : IDL.Text,
  'name' : IDL.Text,
  'badges' : IDL.Vec(IDL.Text),
  'avatarUrl' : IDL.Text,
  'bannerUrl' : IDL.Text,
});
export const LoginPayload = IDL.Record({
  'password' : IDL.Text,
  'loginIdentifier' : IDL.Text,
});
export const Session = IDL.Record({
  'token' : IDL.Text,
  'expiresAt' : IDL.Int,
  'email' : IDL.Text,
});
export const RegisterPayload = IDL.Record({
  'username' : IDL.Text,
  'password' : IDL.Text,
  'email' : IDL.Text,
});
export const RegistrationError = IDL.Variant({
  'emailTaken' : IDL.Null,
  'alreadyRegistered' : IDL.Null,
  'unknown' : IDL.Null,
  'usernameTaken' : IDL.Null,
});
export const RegistrationResult = IDL.Variant({
  'error' : RegistrationError,
  'success' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([LoginPayload], [IDL.Opt(Session)], []),
  'register' : IDL.Func([RegisterPayload], [RegistrationResult], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'customStatus' : IDL.Text,
    'aboutMe' : IDL.Text,
    'name' : IDL.Text,
    'badges' : IDL.Vec(IDL.Text),
    'avatarUrl' : IDL.Text,
    'bannerUrl' : IDL.Text,
  });
  const LoginPayload = IDL.Record({
    'password' : IDL.Text,
    'loginIdentifier' : IDL.Text,
  });
  const Session = IDL.Record({
    'token' : IDL.Text,
    'expiresAt' : IDL.Int,
    'email' : IDL.Text,
  });
  const RegisterPayload = IDL.Record({
    'username' : IDL.Text,
    'password' : IDL.Text,
    'email' : IDL.Text,
  });
  const RegistrationError = IDL.Variant({
    'emailTaken' : IDL.Null,
    'alreadyRegistered' : IDL.Null,
    'unknown' : IDL.Null,
    'usernameTaken' : IDL.Null,
  });
  const RegistrationResult = IDL.Variant({
    'error' : RegistrationError,
    'success' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([LoginPayload], [IDL.Opt(Session)], []),
    'register' : IDL.Func([RegisterPayload], [RegistrationResult], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };