/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : string,
  'name' : string,
  'serverId' : string,
}
export interface Channel {
  'id' : string,
  'categoryId' : string,
  'channelType' : ChannelType,
  'name' : string,
  'serverId' : string,
}
export type ChannelType = { 'voice' : null } |
  { 'text' : null };
export interface CreateServerPayload {
  'name' : string,
  'description' : string,
  'bannerURL' : string,
  'isPublic' : boolean,
  'iconURL' : string,
}
export interface RegisterPayload {
  'username' : string,
  'password' : string,
  'email' : string,
}
export type RegistrationError = { 'emailTaken' : null } |
  { 'roleAssignmentFailed' : null } |
  { 'alreadyRegistered' : null } |
  { 'unknown' : null } |
  { 'usernameTaken' : null };
export type RegistrationResult = { 'error' : RegistrationError } |
  { 'success' : null };
export interface Server {
  'id' : string,
  'name' : string,
  'description' : string,
  'bannerURL' : string,
  'isPublic' : boolean,
  'iconURL' : string,
}
export interface UserProfile {
  'customStatus' : string,
  'aboutMe' : string,
  'name' : string,
  'badges' : Array<string>,
  'avatarUrl' : string,
  'bannerUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTextChannelToCategory' : ActorMethod<[string, string, string], Channel>,
  'addVoiceChannelToCategory' : ActorMethod<[string, string, string], Channel>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string, string], Category>,
  'createServer' : ActorMethod<[CreateServerPayload], Server>,
  'deleteCategory' : ActorMethod<[string, string], undefined>,
  'getAllServers' : ActorMethod<[], Array<Server>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[string], Array<Category>>,
  'getServer' : ActorMethod<[string], [] | [Server]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'register' : ActorMethod<[RegisterPayload], RegistrationResult>,
  'renameCategory' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCategoryOrder' : ActorMethod<[string, Array<string>], undefined>,
  'setChannelOrder' : ActorMethod<[string, string, Array<string>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];