/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VoiceChannel {
    id: bigint;
    name: string;
}
export interface Server {
    id: bigint;
    members: Array<ServerMember>;
    owner: Principal;
    name: string;
    description: string;
    channels: Array<ChannelCategory>;
    communityMode: boolean;
    bannerUrl: string;
    iconUrl: string;
    roles: Array<Role>;
}
export interface Role {
    id: bigint;
    permissions: Array<Permission>;
    name: string;
    color: string;
    position: bigint;
}
export interface FriendRequest {
    to: Principal;
    from: Principal;
    timestamp: bigint;
}
export interface ServerMember {
    userId: Principal;
    joinedAt: bigint;
    roles: Array<bigint>;
}
export interface ChannelCategory {
    id: bigint;
    name: string;
    voiceChannels: Array<VoiceChannel>;
    isExpanded: boolean;
    textChannels: Array<TextChannel>;
}
export interface VoiceChannelPresence {
    userId: Principal;
    joinedAt: bigint;
    voiceChannelId: bigint;
    serverId: bigint;
}
export interface TextChannelMessage {
    id: bigint;
    content: string;
    createdAt: bigint;
    createdBy: Principal;
    isPersistent: boolean;
    textChannelId: bigint;
    serverId: bigint;
}
export interface Permission {
    value: boolean;
    name: string;
}
export interface TextChannel {
    id: bigint;
    name: string;
}
export interface UserProfile {
    customStatus: string;
    aboutMe: string;
    name: string;
    badges: Array<string>;
    avatarUrl: string;
    bannerUrl: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserStatus {
    Idle = "Idle",
    Online = "Online",
    Invisible = "Invisible",
    DoNotDisturb = "DoNotDisturb"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptFriendRequest(from: Principal): Promise<void>;
    addCategoryToServer(serverId: bigint, categoryName: string): Promise<bigint>;
    addRole(serverId: bigint, _name: string, color: string, permissions: Array<Permission>): Promise<bigint>;
    addTextChannel(serverId: bigint, categoryId: bigint, channelName: string): Promise<bigint>;
    addVoiceChannel(serverId: bigint, categoryId: bigint, channelName: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignRoleToUser(serverId: bigint, _roleId: bigint, _user: Principal): Promise<void>;
    blockUser(user: Principal): Promise<void>;
    createServer(_name: string, description: string): Promise<bigint>;
    declineFriendRequest(from: Principal): Promise<void>;
    discoverServers(): Promise<Array<Server>>;
    getAllServers(): Promise<Array<Server>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCallerUsername(): Promise<string | null>;
    getCategories(serverId: bigint): Promise<Array<ChannelCategory>>;
    getFriendRequests(): Promise<Array<FriendRequest>>;
    getFriends(): Promise<Array<Principal>>;
    getRoles(serverId: bigint): Promise<Array<Role>>;
    getServer(serverId: bigint): Promise<Server>;
    getServerMembers(serverId: bigint): Promise<Array<ServerMember>>;
    getServerOrdering(): Promise<Array<bigint>>;
    getTextChannelMessages(serverId: bigint, textChannelId: bigint, startFromMessageId: bigint | null): Promise<Array<TextChannelMessage>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserStatus(user: Principal): Promise<UserStatus | null>;
    getVoiceChannelParticipants(serverId: bigint, voiceChannelId: bigint): Promise<Array<VoiceChannelPresence>>;
    healthCheck(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    joinServer(serverId: bigint): Promise<void>;
    joinVoiceChannel(serverId: bigint, voiceChannelId: bigint): Promise<void>;
    leaveServer(serverId: bigint): Promise<void>;
    leaveVoiceChannel(serverId: bigint, voiceChannelId: bigint): Promise<void>;
    removeFriend(friend: Principal): Promise<void>;
    removeRoleFromUser(serverId: bigint, _roleId: bigint, _user: Principal): Promise<void>;
    renameServer(serverId: bigint, newName: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendFriendRequest(to: Principal): Promise<void>;
    sendTextChannelMessage(serverId: bigint, textChannelId: bigint, content: string): Promise<bigint>;
    setRolePermissions(serverId: bigint, _roleId: bigint, _permissions: Array<Permission>): Promise<void>;
    setServerOrdering(ordering: Array<bigint>): Promise<void>;
    setUserStatus(status: UserStatus): Promise<void>;
    setUsername(desiredUsername: string): Promise<void>;
    updateServerSettings(serverId: bigint, description: string, bannerUrl: string, iconUrl: string, communityMode: boolean): Promise<void>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole, UserStatus as _UserStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptFriendRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptFriendRequest(arg0);
            return result;
        }
    }
    async addCategoryToServer(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategoryToServer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategoryToServer(arg0, arg1);
            return result;
        }
    }
    async addRole(arg0: bigint, arg1: string, arg2: string, arg3: Array<Permission>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addRole(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRole(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addTextChannel(arg0: bigint, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTextChannel(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTextChannel(arg0, arg1, arg2);
            return result;
        }
    }
    async addVoiceChannel(arg0: bigint, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addVoiceChannel(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVoiceChannel(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignRoleToUser(arg0: bigint, arg1: bigint, arg2: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRoleToUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRoleToUser(arg0, arg1, arg2);
            return result;
        }
    }
    async blockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async createServer(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createServer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createServer(arg0, arg1);
            return result;
        }
    }
    async declineFriendRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.declineFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineFriendRequest(arg0);
            return result;
        }
    }
    async discoverServers(): Promise<Array<Server>> {
        if (this.processError) {
            try {
                const result = await this.actor.discoverServers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.discoverServers();
            return result;
        }
    }
    async getAllServers(): Promise<Array<Server>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUsername(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUsername();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUsername();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(arg0: bigint): Promise<Array<ChannelCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories(arg0);
            return result;
        }
    }
    async getFriendRequests(): Promise<Array<FriendRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendRequests();
            return result;
        }
    }
    async getFriends(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriends();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriends();
            return result;
        }
    }
    async getRoles(arg0: bigint): Promise<Array<Role>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoles(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoles(arg0);
            return result;
        }
    }
    async getServer(arg0: bigint): Promise<Server> {
        if (this.processError) {
            try {
                const result = await this.actor.getServer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServer(arg0);
            return result;
        }
    }
    async getServerMembers(arg0: bigint): Promise<Array<ServerMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServerMembers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServerMembers(arg0);
            return result;
        }
    }
    async getServerOrdering(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServerOrdering();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServerOrdering();
            return result;
        }
    }
    async getTextChannelMessages(arg0: bigint, arg1: bigint, arg2: bigint | null): Promise<Array<TextChannelMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTextChannelMessages(arg0, arg1, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTextChannelMessages(arg0, arg1, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserStatus(arg0: Principal): Promise<UserStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStatus(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStatus(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVoiceChannelParticipants(arg0: bigint, arg1: bigint): Promise<Array<VoiceChannelPresence>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVoiceChannelParticipants(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVoiceChannelParticipants(arg0, arg1);
            return result;
        }
    }
    async healthCheck(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.healthCheck();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.healthCheck();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinServer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinServer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinServer(arg0);
            return result;
        }
    }
    async joinVoiceChannel(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinVoiceChannel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinVoiceChannel(arg0, arg1);
            return result;
        }
    }
    async leaveServer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveServer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveServer(arg0);
            return result;
        }
    }
    async leaveVoiceChannel(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveVoiceChannel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveVoiceChannel(arg0, arg1);
            return result;
        }
    }
    async removeFriend(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFriend(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFriend(arg0);
            return result;
        }
    }
    async removeRoleFromUser(arg0: bigint, arg1: bigint, arg2: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeRoleFromUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeRoleFromUser(arg0, arg1, arg2);
            return result;
        }
    }
    async renameServer(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.renameServer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameServer(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendFriendRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendFriendRequest(arg0);
            return result;
        }
    }
    async sendTextChannelMessage(arg0: bigint, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendTextChannelMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendTextChannelMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async setRolePermissions(arg0: bigint, arg1: bigint, arg2: Array<Permission>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRolePermissions(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRolePermissions(arg0, arg1, arg2);
            return result;
        }
    }
    async setServerOrdering(arg0: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setServerOrdering(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setServerOrdering(arg0);
            return result;
        }
    }
    async setUserStatus(arg0: UserStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserStatus(to_candid_UserStatus_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserStatus(to_candid_UserStatus_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setUsername(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUsername(arg0);
            return result;
        }
    }
    async updateServerSettings(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateServerSettings(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateServerSettings(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatus): UserStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserStatus]): UserStatus | null {
    return value.length === 0 ? null : from_candid_UserStatus_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Idle: null;
} | {
    Online: null;
} | {
    Invisible: null;
} | {
    DoNotDisturb: null;
}): UserStatus {
    return "Idle" in value ? UserStatus.Idle : "Online" in value ? UserStatus.Online : "Invisible" in value ? UserStatus.Invisible : "DoNotDisturb" in value ? UserStatus.DoNotDisturb : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): _UserStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): {
    Idle: null;
} | {
    Online: null;
} | {
    Invisible: null;
} | {
    DoNotDisturb: null;
} {
    return value == UserStatus.Idle ? {
        Idle: null
    } : value == UserStatus.Online ? {
        Online: null
    } : value == UserStatus.Invisible ? {
        Invisible: null
    } : value == UserStatus.DoNotDisturb ? {
        DoNotDisturb: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
